# Generated by Django 3.2 on 2021-11-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
