# Generated by Django 3.2 on 2021-11-13 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Collection',
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='follow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfollow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(default='http://3.25.207.134/adali1636720856000_avatar.png', max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('user', 'recipe')},
        ),
    ]
